"use client";

import { useCallback, useState } from "react";
import { useToast } from "@/components/providers/ToastProvider";
import { fetchExecutiveSummary, isApiConfigured } from "@/lib/api";
import type { AnalysisResult } from "@/types";

/**
 * Generates a styled PDF from the dashboard.
 * Uses jsPDF + html2canvas (only loaded on demand to keep the initial bundle small).
 */
export function useExport(targetId: string, data: AnalysisResult | null) {
  const [exporting, setExporting] = useState(false);
  const { show } = useToast();

  const exportPdf = useCallback(async () => {
    if (!data) return;
    setExporting(true);
    try {
      const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
        import("html2canvas"),
        import("jspdf"),
      ]);

      const target = document.getElementById(targetId);
      if (!target) throw new Error("Dashboard not ready");

      // Temporarily hide elements we don't want in the snapshot.
      const hiddens = target.querySelectorAll<HTMLElement>("[data-pdf-hide]");
      hiddens.forEach((el) => (el.style.visibility = "hidden"));

      const canvas = await html2canvas(target, {
        backgroundColor: getComputedStyle(document.documentElement).getPropertyValue("--bg-base").trim() || "#0a0a0f",
        scale: 2,
        useCORS: true,
        logging: false,
      });

      hiddens.forEach((el) => (el.style.visibility = ""));

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });

      // Cover page
      pdf.setFontSize(28);
      pdf.text(data.meta.filename, 40, 60);
      pdf.setFontSize(11);
      pdf.setTextColor(120);
      pdf.text(`Generated by Lumen BI · ${new Date().toLocaleString()}`, 40, 80);

      pdf.setFontSize(13);
      pdf.setTextColor(0);
      pdf.text("Executive summary", 40, 120);
      pdf.setFontSize(10);
      pdf.setTextColor(60);
      let summary = `Across ${data.meta.row_count.toLocaleString()} rows and ${
        data.meta.column_count
      } columns, key metrics show: ${data.kpis
        .map((k) => `${k.label} — ${k.format === "percent" ? `${(k.value * 100).toFixed(1)}%` : k.value.toLocaleString()}`)
        .join("; ")}. ${data.anomalies.length} statistical anomalies were detected.`;
      if (isApiConfigured()) {
        try {
          const ai = await fetchExecutiveSummary(data.meta.id);
          if (ai.trim()) summary = ai.trim();
        } catch {
          /* keep deterministic fallback */
        }
      }
      pdf.text(pdf.splitTextToSize(summary, 520), 40, 140);

      pdf.addPage();
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const ratio = canvas.height / canvas.width;
      const w = pageWidth - 40;
      const h = Math.min(w * ratio, pageHeight - 80);
      pdf.addImage(imgData, "PNG", 20, 40, w, h);

      pdf.save(`${data.meta.filename.replace(/\.[^.]+$/, "")}-report.pdf`);
      show({
        variant: "success",
        title: "Report downloaded",
        description: "Your PDF is ready to share.",
      });
    } catch (err) {
      show({
        variant: "error",
        title: "Export failed",
        description: err instanceof Error ? err.message : "Please try again.",
      });
    } finally {
      setExporting(false);
    }
  }, [data, show, targetId]);

  return { exporting, exportPdf };
}
